- alias: Notify when the washer finished
  trigger:
  - platform: template
    value_template: '{% if states(''sensor.washerpower'') == ''3'' -%}true{%endif%}'
  action:
  - service: light.turn_on
    data:
      entity_id: light.right_notification_light
      brightness: 255
      effect: WhatsApp
  - service: notify.livingroom_tv
    data:
      message: "Waschmaschine fertig"
      data:
        icon: "www/washer.png"

  # - service: light.turn_on
  #   data:
  #     entity_id: light.left_notification_light
  #     brightness: 255
  #     effect: WhatsApp
  id: 03d218ea839a4d6f8adf1942072db7e0
- alias: Notify when the dryer finished
  trigger:
  - platform: template
    value_template: '{% if states(''sensor.dryerpower'') == ''3'' -%}true{%endif%}'
  action:
  - service: light.turn_on
    data:
      entity_id: light.right_notification_light
      brightness: 255
      effect: Twitter
  - service: light.turn_on
    data:
      entity_id: light.left_notification_light
      brightness: 255
      effect: Twitter
  id: 437077c1dd9441fb8486235425dde55a
- alias: Badezimmer Musik - an
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001e54426
    from: 'off'
    to: 'on'
  condition:
    condition: numeric_state
    entity_id: sensor.motion_sensor_158d0001e54426
    above: 40
  action:
  - service: media_player.media_play
    entity_id: media_player.badezimmer
  id: f7ad2559a6144e3680493d8120b13a80
- alias: Badezimmer Musik - aus
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d0001e54426
    from: 'on'
    to: 'off'
    for:
      seconds: 0.1
  - platform: numeric_state
    entity_id: sensor.illumination_158d0001e54426
    below: 40
  action:
  - service: media_player.media_pause
    entity_id: media_player.badezimmer
  id: 0293aa59c11c4b2ba5d419357df6c66e
# Sofa Button
- alias: Xiaomi Aqara Switch - Sofa - einfacher Klick - Musik Start / Stop
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00022423e9
      click_type: single
  action:
    service: media_player.media_play_pause
    entity_id: media_player.wohnzimmer
  id: dc40fb2d07db4025a13f98be81d1d304
- alias: Xiaomi Aqara Switch - Sofa - doppel Klick - Musik next
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00022423e9
      click_type: double
  action:
    service: media_player.media_next_track
    entity_id: media_player.spotify
  id: a1a6d0a2e29c4e72a4965ee8501dec28
- alias: Xiaomi Aqara Switch - Sofa - langer Klick - Licht TV
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00022423e9
      click_type: long_click_press
  action:
    service: light.toggle
    entity_id: light.notification_tv_light
  id: 9bf5556c6aa54cfcb23787727c1d5bd9

# Bett Button
- alias: Xiaomi Aqara Switch - Bett - einfacher Klick - Musik Start / Stop
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0002287e2b
      click_type: single
  action:
    service: media_player.media_play_pause
    entity_id: media_player.wohnzimmer
- alias: Xiaomi Aqara Switch - Bett - doppel Klick - Musik next
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0002287e2b
      click_type: double
  action:
    service: media_player.media_next_track
    entity_id: media_player.spotify
- alias: Xiaomi Aqara Switch - Bett - langer Klick - Licht Sofa
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0002287e2b
      click_type: long_click_press
  action:
    service: switch.toggle
    entity_id: switch.floor_lamp

# Fensterkontakt
- alias: Terassentür öffnen
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001f39476
    from: 'off'
    to: 'on'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.temperature_livingroom
        value: "{{ state_attr('climate.wohnzimmer_thermostat_1', 'temperature') }}"
    - service: climate.set_temperature
      data:
        entity_id: climate.wohnzimmer_thermostat_1
        temperature: "12"

- alias: Terassentür schließen
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001f39476
    from: 'on'
    to: 'off'
  action:
    service: climate.set_temperature
    data_template:
      entity_id: climate.wohnzimmer_thermostat_1
      temperature: "{{ states.input_number.temperature_livingroom.state | float }}"


- alias: Xbox Festplatte einschalten
  trigger:
    platform: template
    # value_template: "{% if not is_state('media_player.lg_fernseher', 'off') and is_state_attr('media_player.lg_fernseher', 'source', 'HDMI-1')%}true{% endif %}"
    value_template: "{% if is_state('media_player.living_room_xbox_one', 'on') %}true{% endif %}"
  action:
    - service: switch.turn_on
      entity_id: switch.tv
    - service: media_player.turn_on
      entity_id: media_player.lg_fernseher

- alias: Xbox Festplatte ausschalten
  trigger:
    platform: template
    # value_template: "{% if is_state('media_player.lg_fernseher', 'off') and is_state('media_player.living_room_xbox_one', 'off') %}true{% endif %}"
    value_template: "{% if is_state('media_player.living_room_xbox_one', 'off') %}true{% endif %}"
  action:
    - service: switch.turn_off
      entity_id: switch.tv
    - service: media_player.turn_off
      entity_id: media_player.lg_fernseher

- alias: Xbox Einschalten bei HDMI-1
  trigger:
    platform: template
    value_template: "{% if is_state_attr('media_player.lg_fernseher', 'source', 'MICROSOFT') %}true{% endif %}"
  action:
    service: media_player.turn_on
    entity_id: media_player.living_room_xbox_one
    
    # platform: state
    # entity_id: media_player.lg_fernseher
