homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml


#---GUI----------------------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------------
# Enables the frontend
frontend:
  themes:
    dark-mode:
      primary-color: black
    happy:
      primary-color: pink
    sad:
      primary-color: blue

# Enables configuration UI
config:

# Checks for available updates
updater:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# enables `wake_on_lan` domain
wake_on_lan:


#---Server-------------------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------------
http:
  api_password: !secret http_password
  ssl_certificate: /ssl/certificate.pem
  ssl_key: /ssl/privkey.pem


#---General------------------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------------
# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# Enables Logger
logger:

# MQTT Broker
mqtt:
  broker: 127.0.0.1
  username: HomeAssi
  password: REYph5Pp6zK8
#   username: !secret mqtt_username
#   password: !secret mqtt_password


#---Smarthome----------------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------------

#---Files--------------------------------------------------------------------------------------------------------------
scene: !include scenes.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
# script: !include scripts.yaml
switch: !include switches.yaml
light: !include lights.yaml

#---Devices------------------------------------------------------------------------------------------------------------
# Vacuum
# vacuum:
#  - platform: xiaomi_miio
#    host: !secret vacuum_robot_ip
#    token: !secret vacuum_robot_token

# Mediaplayer
media_player:
  # - platform: cast
  #   host: 192.168.178.29
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: cast
    host: 192.168.178.202
  # - platform: kodi
  #   host: 192.168.178.36
  - platform: webostv
    host: 192.168.178.22
    name: LG Fernseher
    customize:
      sources:
        - hdmi1
        - youtube
        - 'Amazon Prime Video'
        - netflix
        - dazn
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: "7C-1C-4E-55-FE-0E"
  - platform: xboxone
    name: Living Room Xbox One
    device: !secret xbox_one_id
    # ip_address: 192.168.178.10

#Thermostat
maxcube:
  gateways:
    - host: 192.168.178.203

device_tracker:
  - platform: fritz
    host: 192.168.178.1

#Xiaomi Aqara
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_aqara_gateway_key

#---Other--------------------------------------------------------------------------------------------------------------
# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Zone
zone:
  - name: Home
    latitude: !secret zone_home_latitude
    longitude: !secret zone_home_longitude
    radius: 10
    icon: mdi:home
  - name: Work
    latitude: !secret zone_work_latitude
    longitude: !secret zone_work_longitude
    radius: 50
    icon: mdi:worker

weather:
  - platform: yweather

openuv:
  api_key: !secret openuv_api_key


notify:
  - platform: webostv
    host: 192.168.178.22
    name: livingroom_tv



input_number:
  temperature_livingroom:
    name: Wohnzimmer Temperatur
    initial: 20
    min: 5
    max: 35
    step: 1
