homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml


#---GUI----------------------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------------
# Enables the frontend
frontend:

# Enables configuration UI
config:

# Checks for available updates
updater:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:


#---Server-------------------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------------
http:
  api_password: !secret http_password
  ssl_certificate: /ssl/certificate.pem
  ssl_key: /ssl/privkey.pem


#---General------------------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------------
# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# Enables Logger
logger:

# MQTT Broker
mqtt:
  broker: 127.0.0.1
#   username: !secret mqtt_username
#   password: !secret mqtt_password


#---Smarthome----------------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------------

#---Files--------------------------------------------------------------------------------------------------------------
scene: !include scenes.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
# script: !include scripts.yaml
switch: !include switches.yaml
light: !include lights.yaml

#---Devices------------------------------------------------------------------------------------------------------------
# Vacuum
vacuum:
 - platform: xiaomi_miio
   host: !secret vacuum_robot_ip
   token: !secret vacuum_robot_token

# Mediaplayer
media_player:
  # - platform: cast
  #   host: 192.168.178.29
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  # - platform: kodi
  #   host: 192.168.178.36

#Thermostat
maxcube:
   host: 192.168.178.38

device_tracker:
  - platform: fritz
    host: 192.168.178.1


#---Other--------------------------------------------------------------------------------------------------------------
# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Zone
zone:
  - name: Home
    latitude: !secret zone_home_latitude
    longitude: !secret zone_home_longitude
    radius: 10
    icon: mdi:home
  - name: Work
    latitude: !secret zone_work_latitude
    longitude: !secret zone_work_longitude
    radius: 50
    icon: mdi:worker

# Google Assistant
google_assistant:
  project_id: homeassistant-4d1f3
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  agent_user_id: !secret google_agent_user_id
  api_key: [an API Key generated for the Google Actions project]
  expose_by_default: false
  entity_config: !include google_entity.yaml

# Google Calendar
#google:
#  client_id: !secret google_client_id
#  client_secret: !secret google_client_secret
