- platform: yeelight
  devices:
    192.168.178.21:
      name: bathroom ceiling light
      save_on_change: true
    192.168.178.30:
      name: right notification light
      save_on_change: true