#---Electric Meter-----------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------------

#---Television---------------------------------------------------------------------------------------------------------
- platform: mqtt
  name: tv energy today
  state_topic: "tele/sonoff_tv/SENSOR"
  value_template: "{{ value_json.ENERGY.Today }}"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: tv energy yesterday
  state_topic: "tele/sonoff_tv/SENSOR"
  value_template: "{{ value_json.ENERGY.Yesterday }}"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: tv energy total
  state_topic: "tele/sonoff_tv/SENSOR"
  value_template: "{{ value_json.ENERGY.Total }}"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: tv power
  state_topic: "tele/sonoff_tv/SENSOR"
  value_template: "{{ value_json.ENERGY.Power }}"
  unit_of_measurement: "W"
- platform: mqtt
  name: tv voltage
  state_topic: "tele/sonoff_tv/SENSOR"
  value_template: "{{ value_json.ENERGY.Voltage }}"
  unit_of_measurement: "V"

#---Washer-------------------------------------------------------------------------------------------------------------
- platform: mqtt
  name: washer energy today
  state_topic: "tele/sonoff_washer/SENSOR"
  value_template: "{{ value_json.ENERGY.Today }}"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: washer energy yesterday
  state_topic: "tele/sonoff_washer/SENSOR"
  value_template: "{{ value_json.ENERGY.Yesterday }}"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: washer energy total
  state_topic: "tele/sonoff_washer/SENSOR"
  value_template: "{{ value_json.ENERGY.Total }}"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: washer power
  state_topic: "tele/sonoff_washer/SENSOR"
  value_template: "{{ value_json.ENERGY.Power }}"
  unit_of_measurement: "W"
- platform: mqtt
  name: washer voltage
  state_topic: "tele/sonoff_washer/SENSOR"
  value_template: "{{ value_json.ENERGY.Voltage }}"
  unit_of_measurement: "V"

#---Dryer--------------------------------------------------------------------------------------------------------------
- platform: mqtt
  name: dryer energy today
  state_topic: "tele/sonoff_dryer/SENSOR"
  value_template: "{{ value_json.ENERGY.Today }}"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: dryer energy yesterday
  state_topic: "tele/sonoff_dryer/SENSOR"
  value_template: "{{ value_json.ENERGY.Yesterday }}"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: dryer energy total
  state_topic: "tele/sonoff_dryer/SENSOR"
  value_template: "{{ value_json.ENERGY.Total }}"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: dryer power
  state_topic: "tele/sonoff_dryer/SENSOR"
  value_template: "{{ value_json.ENERGY.Power }}"
  unit_of_measurement: "W"
- platform: mqtt
  name: dryer voltage
  state_topic: "tele/sonoff_dryer/SENSOR"
  value_template: "{{ value_json.ENERGY.Voltage }}"
  unit_of_measurement: "V"



#---Climate------------------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------------


#---Livingroom---------------------------------------------------------------------------------------------------------
- platform: mqtt
  name: livingroom temperature
  state_topic: "tele/sonoff_lightmiddle/SENSOR"
  value_template: "{{ value_json.AM2301.Temperature }}"
  unit_of_measurement: "°C"
- platform: mqtt
  name: livingroom humidity
  state_topic: "tele/sonoff_lightmiddle/SENSOR"
  value_template: "{{ value_json.AM2301.Humidity }}"
  unit_of_measurement: "%"



#---Other--------------------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------------

#---Weather------------------------------------------------------------------------------------------------------------
- platform: yr
  name: weather
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - humidity

#---System-------------------------------------------------------------------------------------------------------------
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use

#---Device Trackers----------------------------------------------------------------------------------------------------
- platform: fritzbox_netmonitor
  host: 192.168.178.1

#---HiGrow Plantmeter--------------------------------------------------------------------------------------------------
- platform: mqtt
  name: higrow temperature
  state_topic: "tele/HiGrow1/SENSOR"
  value_template: "{{ value_json.temperature }}"
  unit_of_measurement: "°C"
- platform: mqtt
  name: higrow soil
  state_topic: "tele/HiGrow1/SENSOR"
  value_template: "{{ value_json.water }}"
  unit_of_measurement: ""
- platform: mqtt
  name: higrow humidity
  state_topic: "tele/HiGrow1/SENSOR"
  value_template: "{{ value_json.humidity }}"
  unit_of_measurement: "%"