- platform: mqtt
  name: floor lamp
  command_topic: "cmnd/sonoff_lightmiddle/power"
  state_topic: "stat/sonoff_lightmiddle/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: tv
  command_topic: "cmnd/sonoff_tv/power"
  state_topic: "stat/sonoff_tv/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: robo station
  command_topic: "cmnd/sonoff_robotStation/power"
  state_topic: "stat/sonoff_robotStation/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: music
  command_topic: "cmnd/sonoff_music/power"
  state_topic: "stat/sonoff_music/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: washer
  command_topic: "cmnd/sonoff_washer/power"
  state_topic: "stat/sonoff_washer/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: dryer
  command_topic: "cmnd/sonoff_dryer/power"
  state_topic: "stat/sonoff_dryer/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: Steckdose_1
  command_topic: "socket/switch1/set"
  state_topic: "socket/switch1/status"
  payload_on: "1"
  payload_off: "0"